server:
  port: ${PORT:8080}

cors:
  originPatterns: http://localhost:8080,http://localhost:3000

file:
  upload-dir: /Code/UploadDir

security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000

email:
  subject: "Default Subject"
  message: "Default Message"

spring:
  application:
    name: rest-project-with-spring-boot-java-reactjs

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_api_springboot?useTimezone=true&serverTimezone=UTC
    username: leonardo
    password: user1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  mail:
    host: smtp.gmail.com
    port: 587
    username: leocavalhere6@gmail.com
    password: abcd efgh ijkl mnop
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

spring-doc:
  paths-to-match:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true
